// Build-time app/version/git metadata for a Dynatrace App (dt-app / esbuild).
//
// dt-app builds with esbuild (not Vite), so instead of a Vite `define` block we
// generate a small TypeScript module the UI imports. `getBuildInfo()` is exported
// so it can also be consumed by tooling if desired.
//
// Run via the npm `prebuild`/`predeploy`/`prestart` hooks (see SKILL.md). Running
// this file directly writes the generated module (ui/app/generated/build-info.ts).

import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Where the generated module is written. Matches this app's UI source layout.
const OUT_DIR = resolve(ROOT, "ui/app/generated");

function git(command, fallback) {
  try {
    return execSync(command, { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

function readJson(relativePath) {
  try {
    return JSON.parse(readFileSync(resolve(ROOT, relativePath), "utf8"));
  } catch {
    return null;
  }
}

/** @returns {{ version: string, commitHash: string, commitDate: string }} */
export function getBuildInfo() {
  // Version source of truth: the deployed app manifest (app.config.json).
  // Fall back to the tracked example config, then package.json, then a default.
  const appConfig =
    readJson("app.config.json") ?? readJson("app.config.example.json");
  const pkg = readJson("package.json");
  const version = appConfig?.app?.version || pkg?.version || "0.0.0";

  const commitHash = git("git rev-parse --short HEAD", "unknown");
  const commitDate = git("git log -1 --format=%cI", "");

  return { version, commitHash, commitDate };
}

function writeGeneratedModule(info) {
  mkdirSync(OUT_DIR, { recursive: true });
  const contents =
    "// AUTO-GENERATED by scripts/build-info.mjs — do not edit.\n" +
    "// Regenerated on every build via the npm prebuild/predeploy/prestart hooks.\n" +
    `export const APP_VERSION = ${JSON.stringify(info.version)};\n` +
    `export const COMMIT_HASH = ${JSON.stringify(info.commitHash)};\n` +
    `export const COMMIT_DATE = ${JSON.stringify(info.commitDate)};\n`;
  writeFileSync(resolve(OUT_DIR, "build-info.ts"), contents);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const info = getBuildInfo();
  writeGeneratedModule(info);
  console.log(
    `[build-info] v${info.version} · ${info.commitHash} · ${info.commitDate || "no-date"}`
  );
}
